### ISSUE TITLE
Dropframe tc issue when setting seconds to ##:##:59:00 - ##:##:59:29

### ISSUE THREAD

**Issue by pjdicke** [reidransom/timecode.js#3]
**init with timecode ending in ##:##:59:00 - ##:##:59:29 seconds**

var tc = timecode.init({framerate:29.97002997002997, timecode: **'00:17:59:29'**, drop_frame: true});
tc.toString()
**"00:18:00;01"** _// should be 00:17:59:29_

var tc = timecode.init({framerate:29.97002997002997, timecode: **'00:17:59:28'**, drop_frame: true});
tc.toString()
**"00:18:00;00"** _// should be 00:17:59:28_

var tc = timecode.init({framerate:29.97002997002997, timecode: **'00:17:59:27'**, drop_frame: true});
tc.toString()
**"00:17:59;29"** _// should be 00:17:59:27_

var tc = timecode.init({framerate:29.97002997002997, timecode: **'00:17:59:26'**, drop_frame: true});
tc.toString()
**"00:17:59;28"** _// should be 00:17:59:26_

var tc = timecode.init({framerate:29.97002997002997, timecode: **'00:17:59:25'**, drop_frame: true});
tc.toString()
**"00:17:59;27"** _// should be 00:17:59:25_

var tc = timecode.init({framerate:29.97002997002997, timecode: **'00:17:59:24'**, drop_frame: true});
tc.toString()
**"00:17:59;26"** _// should be 00:17:59:24_

var tc = timecode.init({framerate:29.97002997002997, timecode: **'00:17:58:24'**, drop_frame: true});
tc.toString()
**"00:17:58;24"** _//  CORRECT!_

var tc = timecode.init({framerate:29.97002997002997, timecode: **'00:17:58:29'**, drop_frame: true});
tc.toString()
**"00:17:58;29"** _//  CORRECT!_

**Comment by reidransom** [comment]
see #4
