### ISSUE TITLE
Dropframe isn't accurate

### ISSUE THREAD

**Issue by pjdicke** [reidransom/timecode.js#4]
According to our video guy the dropframe just isn't working correctly here. 

This video supports his claim as well https://www.youtube.com/watch?v=ykjyNeuQROU 
Screenshot of non vs dropframe timecode transitioning from 00:00:59:29 to 00:01:00;02 

![image](https://cloud.githubusercontent.com/assets/1786442/5845681/0f7eaac2-a18c-11e4-857d-709ffb5b5bd8.png)

In this tool I can't event set a dropframe timecode to 00:00:59:29
var tc = timecode.init({framerate:29.97002997002997, timecode: '00:00:59:29', drop_frame: true});
tc.toString()
"00:01:00;01"  // should be 00:00:59:29

tc.add('00:00:00:01')
tc.toString() // "00:01:00;02"

tc.subtract('00:00:00:01')
tc.toString() // "00:01:00;01" <-- this frame shouldn't exist in dropframe

tc.subtract('00:00:00:01')
tc.toString() // "00:01:00;00" <-- this frame shouldn't exist in dropframe

tc.subtract('00:00:00:01')
tc.toString() // "00:00:59;27" skipped three frames here when trying to minus 1 frame ??

Just a heads for anyone using the dropframe flag.

**Comment by reidransom** [comment]
Thank you for pointing this out Paul.  Dropframe is something I never fully ironed out.  If I recall, it was never more than a couple frames off, which was close enough for my purposes.

**Comment by reidransom** [comment]
Nice!
