### ISSUE TITLE
Error: "'self' is not defined" in function frameNumberToTimecode

### ISSUE THREAD

**Issue by Aelsa** [reidransom/timecode.js#7]
Hi everyone,

I use the Timecode library to determine the duration of my videos. I have a video for which TCin = 23:59:53;16 and TCout = 00:00:05;17. When I run the following code:
```javascript
var dur = timecode.init({
    framerate:   29.97,
    timecode:    00:00:05;17
});
dur.subtract(23:59:53;16);
var nbFrame = dur.frame_count;
```
I had the issue: 'self' is not defined. So I checked the code in timecode.js, and there is a 'self' in the method frameNumberToTimecode, line 82:
```javascript
frame_count = frame_count - (24 * 3600 * self.int_framerate);
```
If I replace this 'self' by a 'this', I have no more error, and the duration seems correct. Do you confirm there is a bug in the timecode.js script, or maybe I did something wrong ?

**Comment by reidransom** [comment]
Sorry about that.  This was fixed at some point and I never updated npm.  d4c48099b
