### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by miguelgrinberg** [reidransom/timecode.js#8]
It would be useful if you can add a LICENSE file to your repository, to make sure we are okay to use it in a commercial application.

Thanks!

**Comment by miguelgrinberg** [comment]
Thank you!

In case you are curious, I have created a small video.js plugin that displays the SMPTE timecode of the video as it plays, and allows the user to seek by typing a new timecode, with all the conversions supported by timecode.js. We plan to open source the plugin, which will be part of a larger commercial application. Below is a small preview of this plugin in action:

![TC demo](http://i.imgur.com/tV4JqGC.gif?1)

Thanks again!

**Comment by reidransom** [comment]
That looks great!  If you want, sent me a link to your plugin when it's ready and I'll add it to my README as a "Projects using" section.
